# Generated by Django 4.1.5 on 2023-01-06 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='created',
        ),
    ]
